services:
  postgres:
    image: postgres:17-alpine
    container_name: chat_postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password@
      POSTGRES_DB: real_time_comunication
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chat_main_network
  restore:
    image: postgres:17-alpine
    container_name: postgres_restore
    volumes:
      - ./backups:/backups # Mount backup directory
      - ./scripts/restore.sh:/restore.sh # Mount restore script
    entrypoint: ["sh", "/restore.sh"] # Execute the restore script
    environment:
      PGPASSWORD: password@ # PostgreSQL password
    depends_on:
      - postgres
    networks:
      - chat_main_network

networks:
  chat_main_network:
    driver: bridge

volumes:
  postgres_data:
